# Generated by Django 3.0.8 on 2020-07-23 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200723_2354'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_item_name', models.CharField(max_length=100)),
                ('qr_code_key', models.CharField(max_length=5000)),
                ('actual_cost', models.FloatField()),
                ('depreciation', models.FloatField()),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_item_created_by', to=settings.AUTH_USER_MODEL)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Department', verbose_name='Department')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_item_modified_by', to=settings.AUTH_USER_MODEL)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Location', verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('repair_request_date', models.DateField(verbose_name='Repair Request Date')),
                ('estimated_delivery_date', models.DateField(verbose_name='Estimated Delivery Date')),
                ('actual_delivery_date', models.DateField(verbose_name='Actual Delivery Date')),
                ('estimated_cost', models.FloatField()),
                ('actual_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_request_approved_by', to='employee.Employee', verbose_name='Approved by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductItem', verbose_name='Product Item')),
                ('responsible_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_employee_id', to='employee.Employee', verbose_name='Responsible Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_value', models.CharField(max_length=100)),
                ('property_details', models.CharField(max_length=500)),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='responsible_employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category_modified_by', to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Product')),
            ],
        ),
    ]
