# Generated by Django 3.0.8 on 2020-07-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_auto_20200723_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True)),
                ('table_name', models.CharField(blank=True, max_length=132)),
                ('table_row', models.BigIntegerField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=16)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'model_change_logs',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Role Name')),
                ('from_date', models.DateTimeField(verbose_name='Start')),
                ('to_date', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('is_additional', models.BooleanField(default=False, verbose_name='Additional')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work_record_created_by', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Designation', verbose_name='Designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Employee')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work_record_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
