# Generated by Django 3.0.8 on 2020-07-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0004_mylog_workrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Logged_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
